function plot_all_superimpose_study_1(data_dir, save_dir)

arguments
    data_dir (1,1) string
    save_dir (1,1) string
end

% Group 1
superimpose_EMG( ...
    fullfile(data_dir, "Serie_1-Group_1-Task_3-Rest-Baseline_(JAECO).csv"), ...
    fullfile(data_dir, "Serie_2-Group_1-Task_13-Rest-Device_(DynAReach).csv"), ...
    fullfile(data_dir, "Serie_3-Group_1-Task_24-Rest-Device_(DynAReach).csv"), ...
    fullfile(data_dir, "Serie_4-Group_1-Task_35-Rest-Device_(DynAReach).csv"), ...
    save_dir ...
    );
superimpose_EMG( ...
    fullfile(data_dir, "Serie_1-Group_1-Task_4-Shoulder_Flexion-Baseline_(JAECO).csv"), ...
    fullfile(data_dir, "Serie_2-Group_1-Task_14-Shoulder_Flexion-Device_(DynAReach).csv"), ...
    fullfile(data_dir, "Serie_3-Group_1-Task_25-Shoulder_Flexion-Device_(DynAReach).csv"), ...
    fullfile(data_dir, "Serie_4-Group_1-Task_36-Shoulder_Flexion-Device_(DynAReach).csv"), ...
    save_dir ...
    );
superimpose_EMG( ...
    fullfile(data_dir, "Serie_1-Group_1-Task_5-Elbow_Flexion-Baseline_(JAECO).csv"), ...
    fullfile(data_dir, "Serie_2-Group_1-Task_15-Elbow_Flexion-Device_(DynAReach).csv"), ...
    fullfile(data_dir, "Serie_3-Group_1-Task_26-Elbow_Flexion-Device_(DynAReach).csv"), ...
    fullfile(data_dir, "Serie_4-Group_1-Task_37-Elbow_Flexion-Device_(DynAReach).csv"), ...
    save_dir ...
    );
% Group 2
superimpose_EMG( ...
    fullfile(data_dir, "Serie_1-Group_2-Task_6-Pointing_Task-Baseline_(JAECO).csv"), ...
    fullfile(data_dir, "Serie_2-Group_2-Task_17-Pointing_Task-Baseline_(JAECO).csv"), ...
    fullfile(data_dir, "Serie_3-Group_2-Task_27-Pointing_Task-Device_(DynAReach).csv"), ...
    fullfile(data_dir, "Serie_4-Group_2-Task_38-Pointing_Task-Device_(DynAReach).csv"), ...
    save_dir ...
    );
superimpose_EMG( ...
    fullfile(data_dir, "Serie_1-Group_2-Task_7-HFT_Large_Light_Objects-Baseline_(JAECO).csv"), ...
    fullfile(data_dir, "Serie_2-Group_2-Task_18-HFT_Large_Light_Objects-Baseline_(JAECO).csv"), ...
    fullfile(data_dir, "Serie_3-Group_2-Task_28-HFT_Large_Light_Objects-Device_(DynAReach).csv"), ...
    fullfile(data_dir, "Serie_4-Group_2-Task_39-HFT_Large_Light_Objects-Device_(DynAReach).csv"), ...
    save_dir ...
    );
superimpose_EMG( ...
    fullfile(data_dir, "Serie_1-Group_2-Task_8-Switch_Joystick_and_Grid_Game-Baseline_(JAECO).csv"), ...
    fullfile(data_dir, "Serie_2-Group_2-Task_19-Switch_Joystick_and_Grid_Game-Baseline_(JAECO).csv"), ...
    fullfile(data_dir, "Serie_3-Group_2-Task_29-Switch_Joystick_and_Grid_Game-Device_(DynAReach).csv"), ...
    fullfile(data_dir, "Serie_4-Group_2-Task_40-Switch_Joystick_and_Grid_Game-Device_(DynAReach).csv"), ...
    save_dir ...
    );
% Group 3
superimpose_EMG( ...
    fullfile(data_dir, "Serie_1-Group_3-Task_9-JAMAR_Palmar_Grip-Baseline_(JAECO).csv"), ...
    fullfile(data_dir, "Serie_2-Group_3-Task_20-JAMAR_Palmar_Grip-Baseline_(JAECO).csv"), ...
    fullfile(data_dir, "Serie_3-Group_3-Task_31-JAMAR_Palmar_Grip-Baseline_(JAECO).csv"), ...
    fullfile(data_dir, "Serie_4-Group_3-Task_41-JAMAR_Palmar_Grip-Device_(DynAReach).csv"), ...
    save_dir ...
    );
superimpose_EMG( ...
    fullfile(data_dir, "Serie_1-Group_3-Task_10-HFT_Feeding_task-Baseline_(JAECO).csv"), ...
    fullfile(data_dir, "Serie_2-Group_3-Task_21-HFT_Feeding_task-Baseline_(JAECO).csv"), ...
    fullfile(data_dir, "Serie_3-Group_3-Task_32-HFT_Feeding_task-Baseline_(JAECO).csv"), ...
    fullfile(data_dir, "Serie_4-Group_3-Task_42-HFT_Feeding_task-Device_(DynAReach).csv"), ...
    save_dir ...
    );
superimpose_EMG( ...
    fullfile(data_dir, "Serie_1-Group_3-Task_11-Box_and_Blocs_Test-Baseline_(JAECO).csv"), ...
    fullfile(data_dir, "Serie_2-Group_3-Task_22-Box_and_Blocs_Test-Baseline_(JAECO).csv"), ...
    fullfile(data_dir, "Serie_3-Group_3-Task_33-Box_and_Blocs_Test-Baseline_(JAECO).csv"), ...
    fullfile(data_dir, "Serie_4-Group_3-Task_43-Box_and_Blocs_Test-Device_(DynAReach).csv"), ...
    save_dir ...
    );

end