function dict = get_titles_RABA_ses2()

    keys = [
        "0039~ab~T3.emt"
        "0039~ab~T4.emt"
        "0039~ab~T5.emt"
        "0039~ab~T6.emt"
        "0039~ab~T7.emt"
        "0039~ab~T8.emt"
        "0039~ab~T9.emt"
        "0039~ab~T10.emt"
        "0039~ab~T11.emt"
        "0039~ab~T13.emt"
        "0039~ab~T14.emt"
        "0039~ab~T15.emt"
        "0039~ab~T17.emt"
        "0039~ab~T18.emt"
        "0039~ab~T19.emt"
        "0039~ab~T20.emt"
        "0039~ab~T21.emt"
        "0039~ab~T22.emt"
        "0039~ab~T24.emt"
        "0039~ab~T25.emt"
        "0039~ab~T26.emt"
        "0039~ab~T27.emt"
        "0039~ab~T28.emt"
        "0039~ab~T29.emt"
        "0039~ab~T31.emt"
        "0039~ab~T32.emt"
        "0039~ab~T33.emt"
        "0039~ab~T35.emt"
        "0039~ab~T36.emt"
        "0039~ab~T37.emt"
        "0039~ab~T38.emt"
        "0039~ab~T39.emt"
        "0039~ab~T40.emt"
        "0039~ab~T41.emt"
        "0039~ab~T42.emt"
        "0039~ab~T43.emt"
    ];

    values = [
        "Serie_1-Group_1-Task_3-Rest-Device_(Chair)"
        "Serie_1-Group_1-Task_4-Shoulder_Flexion-Baseline_(Chair)"
        "Serie_1-Group_1-Task_5-Elbow_Flexion-Baseline_(Chair)"
        "Serie_1-Group_2-Task_6-Pointing_Task-Baseline_(Chair)"
        "Serie_1-Group_2-Task_7-HFT_Large_Light_Objects-Baseline_(Chair)"
        "Serie_1-Group_2-Task_8-Switch_Joystick_and_Grid_Game-Baseline_(Chair)"
        "Serie_1-Group_3-Task_9-JAMAR_Palmar_Grip-Baseline_(Chair)"
        "Serie_1-Group_3-Task_10-HFT_Feeding_task-Baseline_(Chair)"
        "Serie_1-Group_3-Task_11-Box_and_Blocs_Test-Baseline_(Chair)"
    
        "Serie_2-Group_1-Task_13-Rest-Device_(Brace)"
        "Serie_2-Group_1-Task_14-Shoulder_Flexion-Device_(Brace)"
        "Serie_2-Group_1-Task_15-Elbow_Flexion-Device_(Brace)"
        "Serie_2-Group_2-Task_17-Pointing_Task-Baseline_(Chair)"
        "Serie_2-Group_2-Task_18-HFT_Large_Light_Objects-Baseline_(Chair)"
        "Serie_2-Group_2-Task_19-Switch_Joystick_and_Grid_Game-Baseline_(Chair)"
        "Serie_2-Group_3-Task_20-JAMAR_Palmar_Grip-Baseline_(Chair)"
        "Serie_2-Group_3-Task_21-HFT_Feeding_task-Baseline_(Chair)"
        "Serie_2-Group_3-Task_22-Box_and_Blocs_Test-Baseline_(Chair)"
    
        "Serie_3-Group_1-Task_24-Rest-Device_(Brace)"
        "Serie_3-Group_1-Task_25-Shoulder_Flexion-Device_(Brace)"
        "Serie_3-Group_1-Task_26-Elbow_Flexion-Device_(Brace)"
        "Serie_3-Group_2-Task_27-Pointing_Task-Device_(Brace)"
        "Serie_3-Group_2-Task_28-HFT_Large_Light_Objects-Device_(Brace)"
        "Serie_3-Group_2-Task_29-Switch_Joystick_and_Grid_Game-Device_(Brace)"
        "Serie_3-Group_3-Task_31-JAMAR_Palmar_Grip-Baseline_(Chair)"
        "Serie_3-Group_3-Task_32-HFT_Feeding_task-Baseline_(Chair)"
        "Serie_3-Group_3-Task_33-Box_and_Blocs_Test-Baseline_(Chair)"
    
        "Serie_4-Group_1-Task_35-Rest-Device_(Brace)"
        "Serie_4-Group_1-Task_36-Shoulder_Flexion-Device_(Brace)"
        "Serie_4-Group_1-Task_37-Elbow_Flexion-Device_(Brace)"
        "Serie_4-Group_2-Task_38-Pointing_Task-Device_(Brace)"
        "Serie_4-Group_2-Task_39-HFT_Large_Light_Objects-Device_(Brace)"
        "Serie_4-Group_2-Task_40-Switch_Joystick_and_Grid_Game-Device_(Brace)"
        "Serie_4-Group_3-Task_41-JAMAR_Palmar_Grip-Device_(Brace)"
        "Serie_4-Group_3-Task_42-HFT_Feeding_task-Device_(Brace)"
        "Serie_4-Group_3-Task_43-Box_and_Blocs_Test-Device_(Brace)"
    ];

    dict = containers.Map(keys, values);

end