function dict = get_titles_GUEA_ses1()

    keys = [
        "0038~aa~t3.csv"
        "0038~aa~t4.csv"
        "0038~aa~t5.csv"
        "0038~aa~t6.csv"
        "0038~aa~t7.csv"
        "0038~aa~t8.csv"
        "0038~aa~t9.csv"
        "0038~aa~t10.csv"
        "0038~aa~t11.csv"
        "0038~aa~t13.csv"
        "0038~aa~t14.csv"
        "0038~aa~t15.csv"
        "0038~aa~t17.csv"
        "0038~aa~t18.csv"
        "0038~aa~t19.csv"
        "0038~aa~t20.csv"
        "0038~aa~t21.csv"
        "0038~aa~t22.csv"
        "0038~aa~t24.csv"
        "0038~aa~t25.csv"
        "0038~aa~t26.csv"
        "0038~aa~t27.csv"
        "0038~aa~t28.csv"
        "0038~aa~t29.csv"
        "0038~aa~t31.csv"
        "0038~aa~t32.csv"
        "0038~aa~t33.csv"
        "0038~aa~t35.csv"
        "0038~aa~t36.csv"
        "0038~aa~t37.csv"
        "0038~aa~t38.csv"
        "0038~aa~t39.csv"
        "0038~aa~t40.csv"
        "0038~aa~t41.csv"
        "0038~aa~t41bis.csv"
        "0038~aa~t42.csv"
        "0038~aa~t43.csv"
        "0038~aa~t44bonus.csv"
    ];

    values = [
    "Serie_1-Task_group_1-Rest-Baseline_(JAECO)"
    "Serie_1-Task_group_1-Shoulder_Flexion-Baseline_(JAECO)"
    "Serie_1-Task_group_1-Elbow_Flexion-Baseline_(JAECO)"
    "Serie_1-Task_group_2-Pointing_Task-Baseline_(JAECO)"
    "Serie_1-Task_group_2-HFT_Large_Light_Objects-Baseline_(JAECO)"
    "Serie_1-Task_group_2-Switch_Joystick_and_Grid_Game-Baseline_(JAECO)"
    "Serie_1-Task_group_3-JAMAR_Palmar_Grip-Baseline_(JAECO)"
    "Serie_1-Task_group_3-HFT_Feeding_task-Baseline_(JAECO)"
    "Serie_1-Task_group_3-Box_and_Blocs_Test-Baseline_(JAECO)"

    "Serie_2-Task_group_1-Rest-Device_(DynAReach)"
    "Serie_2-Task_group_1-Shoulder_Device_(DynAReach)"
    "Serie_2-Task_group_1-Elbow_Device_(DynAReach)"
    "Serie_2-Task_group_2-Pointing_Task-Baseline_(JAECO)"
    "Serie_2-Task_group_2-HFT_Large_Light_Objects-Baseline_(JAECO)"
    "Serie_2-Task_group_2-Switch_Joystick_and_Grid_Game-Baseline_(JAECO)"
    "Serie_2-Task_group_3-JAMAR_Palmar_Grip-Baseline_(JAECO)"
    "Serie_2-Task_group_3-HFT_Feeding_task-Baseline_(JAECO)"
    "Serie_2-Task_group_3-Box_and_Blocs_Test-Baseline_(JAECO)"

    "Serie_3-Task_group_1-Rest-Device_(DynAReach)"
    "Serie_3-Task_group_1-Shoulder_Flexion-Device_(DynAReach)"
    "Serie_3-Task_group_1-Elbow_Flexion-Device_(DynAReach)"
    "Serie_3-Task_group_2-Pointing_Task-Device_(DynAReach)"
    "Serie_3-Task_group_2-HFT_Large_Light_Objects-Device_(DynAReach)"
    "Serie_3-Task_group_2-Switch_Joystick_and_Grid_Game-Device_(DynAReach)"
    "Serie_3-Task_group_3-JAMAR_Palmar_Grip-Baseline_(JAECO)"
    "Serie_3-Task_group_3-HFT_Feeding_task-Baseline_(JAECO)"
    "Serie_3-Task_group_3-Box_and_Blocs_Test-Baseline_(JAECO)"

    "Serie_4-Task_group_1-Rest-Device_(DynAReach)"
    "Serie_4-Task_group_1-Shoulder_Flexion-Device_(DynAReach)"
    "Serie_4-Task_group_1-Elbow_Flexion-Device_(DynAReach)"
    "Serie_4-Task_group_2-Pointing_Task-Device_(DynAReach)"
    "Serie_4-Task_group_2-HFT_Large_Light_Objects-Device_(DynAReach)"
    "Serie_4-Task_group_2-Switch_Joystick_and_Grid_Game-Device_(DynAReach)"
    "Serie_4-Task_group_3-JAMAR_Palmar_Grip-Device_(DynAReach)"
    "Serie_4-Task_group_3-JAMAR_Palmar_Grip_(BIS)-Device_(DynAReach)"
    "Serie_4-Task_group_3-HFT_Feeding_task-Device_(DynAReach)"
    "Serie_4-Task_group_3-Box_and_Blocs_Test-Device_(DynAReach)"
    "Serie_4-Task_group_3-JAMAR_Palmar_Grip_(Maintained_force)-Device_(DynAReach)"
];

    dict = containers.Map(keys, values);

end