function dict = get_titles_RABA_ses1()

    keys = [
        "0039~aa~t3.emt"
        "0039~aa~t4.emt"
        "0039~aa~t5.emt"
        "0039~aa~t6.emt"
        "0039~aa~t7.emt"
        "0039~aa~t8.emt"
        "0039~aa~t9.emt"
        "0039~aa~t10.emt"
        "0039~aa~t11.emt"
        "0039~aa~t13.emt"
        "0039~aa~t14.emt"
        "0039~aa~t15.emt"
        "0039~aa~t17.emt"
        "0039~aa~t18.emt"
        "0039~aa~t19.emt"
        "0039~aa~t20.emt"
        "0039~aa~t21.emt"
        "0039~aa~t22.emt"
        "0039~aa~t24.emt"
        "0039~aa~t25.emt"
        "0039~aa~t26.emt"
        "0039~aa~t27.emt"
        "0039~aa~t28.emt"
        "0039~aa~t29.emt"
        "0039~aa~t31.emt"
        "0039~aa~t32.emt"
        "0039~aa~t33.emt"
        "0039~aa~t35.emt"
        "0039~aa~t36.emt"
        "0039~aa~t37.emt"
        "0039~aa~t38.emt"
        "0039~aa~t39.emt"
        "0039~aa~t40.emt"
        "0039~aa~t41.emt"
        "0039~aa~t42.emt"
        "0039~aa~t43.emt"
    ];

    values = [
        "Serie_1-Group_1-Task_3-Rest-Baseline_(JAECO)"
        "Serie_1-Group_1-Task_4-Shoulder_Flexion-Baseline_(JAECO)"
        "Serie_1-Group_1-Task_5-Elbow_Flexion-Baseline_(JAECO)"
        "Serie_1-Group_2-Task_6-Pointing_Task-Baseline_(JAECO)"
        "Serie_1-Group_2-Task_7-HFT_Large_Light_Objects-Baseline_(JAECO)"
        "Serie_1-Group_2-Task_8-Switch_Joystick_and_Grid_Game-Baseline_(JAECO)"
        "Serie_1-Group_3-Task_9-JAMAR_Palmar_Grip-Baseline_(JAECO)"
        "Serie_1-Group_3-Task_10-HFT_Feeding_task-Baseline_(JAECO)"
        "Serie_1-Group_3-Task_11-Box_and_Blocs_Test-Baseline_(JAECO)"
    
        "Serie_2-Group_1-Task_13-Rest-Baseline_(JAECO)"
        "Serie_2-Group_1-Task_14-Shoulder_Flexion-Baseline_(JAECO)"
        "Serie_2-Group_1-Task_15-Elbow_Flexion-Baseline_(JAECO)"
        "Serie_2-Group_2-Task_17-Pointing_Task-Baseline_(JAECO)"
        "Serie_2-Group_2-Task_18-HFT_Large_Light_Objects-Baseline_(JAECO)"
        "Serie_2-Group_2-Task_19-Switch_Joystick_and_Grid_Game-Baseline_(JAECO)"
        "Serie_2-Group_3-Task_20-JAMAR_Palmar_Grip-Baseline_(JAECO)"
        "Serie_2-Group_3-Task_21-HFT_Feeding_task-Baseline_(JAECO)"
        "Serie_2-Group_3-Task_22-Box_and_Blocs_Test-Baseline_(JAECO)"
    
        "Serie_3-Group_1-Task_24-Rest-Device_(DynAReach)"
        "Serie_3-Group_1-Task_25-Shoulder_Flexion-Device_(DynAReach)"
        "Serie_3-Group_1-Task_26-Elbow_Flexion-Device_(DynAReach)"
        "Serie_3-Group_2-Task_27-Pointing_Task-Device_(DynAReach)"
        "Serie_3-Group_2-Task_28-HFT_Large_Light_Objects-Device_(DynAReach)"
        "Serie_3-Group_2-Task_29-Switch_Joystick_and_Grid_Game-Device_(DynAReach)"
        "Serie_3-Group_3-Task_31-JAMAR_Palmar_Grip-Device_(DynAReach)"
        "Serie_3-Group_3-Task_32-HFT_Feeding_task-Device_(DynAReach)"
        "Serie_3-Group_3-Task_33-Box_and_Blocs_Test-Device_(DynAReach)"
    
        "Serie_4-Group_1-Task_35-Rest-Device_(DynAReach)"
        "Serie_4-Group_1-Task_36-Shoulder_Flexion-Device_(DynAReach)"
        "Serie_4-Group_1-Task_37-Elbow_Flexion-Device_(DynAReach)"
        "Serie_4-Group_2-Task_38-Pointing_Task-Device_(DynAReach)"
        "Serie_4-Group_2-Task_39-HFT_Large_Light_Objects-Device_(DynAReach)"
        "Serie_4-Group_2-Task_30-Switch_Joystick_and_Grid_Game-Device_(DynAReach)"
        "Serie_4-Group_3-Task_41-JAMAR_Palmar_Grip-Device_(DynAReach)"
        "Serie_4-Group_3-Task_42-HFT_Feeding_task-Device_(DynAReach)"
        "Serie_4-Group_3-Task_43-Box_and_Blocs_Test-Device_(DynAReach)"
    ];

    dict = containers.Map(keys, values);

end