addpath("EMG_utils/")
addpath("files_utils/")
addpath("plots_utils/")
addpath("subject_utils/")

% Load subject info
subjects = get_subject_info();

% Convert .emt files to .csv files
FileNameDict_GUEA_ses1 = get_titles_GUEA_ses1();
emtFolder2csv('../data/GUEA_ses1', FileNameDict_GUEA_ses1);
FileNameDict_RABA_ses1 = get_titles_RABA_ses1();
emtFolder2csv('../data/RABA_ses1', FileNameDict_RABA_ses1);

% Define movement dictionary
movements = dictionary();
movements("Rest") = struct('agoniste', ["Bicep","Tricep"], 'antagoniste', ["DeltAnt","DeltPost"]);
movements("Shoulder_Flexion") = struct('agoniste', "DeltAnt", 'antagoniste', "DeltPost");
movements("Elbow_Flexion") = struct('agoniste', "Bicep", 'antagoniste', "Tricep");
movements("Pointing_Task") = struct('agoniste', ["Tricep","DeltAnt"], 'antagoniste', ["Bicep","DeltPost"]);
movements("HFT_Large_Light_Objects") = struct('agoniste', ["Bicep","DeltAnt"], 'antagoniste', ["Tricep","DeltPost"]);
movements("Switch_Joystick_and_Grid_Game") = struct('agoniste', ["Bicep","DeltAnt"], 'antagoniste', ["Tricep","DeltPost"]);
movements("JAMAR_Palmar_Grip") = struct('agoniste', "Bicep", 'antagoniste', "Tricep");
movements("HFT_Feeding_task") = struct('agoniste', "Bicep", 'antagoniste', "Tricep");
movements("Box_and_Blocs_Test") = struct('agoniste', ["Tricep","DeltAnt"], 'antagoniste', ["Bicep","DeltPost"]);

% ------- SUBJECT 1 / SESSION 1 --------

data_dir = "../data/GUEA_ses1";
files = dir(fullfile(data_dir, '*.csv'));
all_tracks_dir = "../figs/GUEA_ses1/all_tracks";
superimpose_dir = "../figs/GUEA_ses1/superimpose";
CAI_dir = "../figs/GUEA_ses1/CAI";

% -- Build all tracks plot --
fprintf("\nCreating all tracks plots for GUEA_ses1...\n")
for k = 1:numel(files)

    % Construct full input path
    emg_Path = fullfile(files(k).folder, files(k).name);

    % Get file name
    file_name = string(files(k).name);
    
    % Get title
    title = strrep(file_name, '.csv', '');
    save_path = fullfile(all_tracks_dir, title);
    title = strrep(title, '_', ' ');
    title = strrep(title, '-', ' - ');
     
    % Show all tracks
    if file_name == "Serie_3-Group_3-Task_31-JAMAR_Palmar_Grip-Device_(DynAReach).csv"
        plot_tracks(emg_Path, save_path, title, subjects(1).bmi, ...
        BicepTrack=1, TricepTrack=2, AntDeltTrack=5, PostDeltTrack=4)
    else
        plot_tracks(emg_Path, save_path, title, subjects(1).bmi)
    end

end
fprintf("All tracks plots successfully created\n")

% -- Build superimpose plots --
fprintf("\nCreating superimpose plots for GUEA_ses1...\n")
% Group 1
superimpose_EMG( ...
    fullfile(data_dir, "Serie_1-Group_1-Task_3-Rest-Baseline_(JAECO).csv"), ...
    fullfile(data_dir, "Serie_2-Group_1-Task_13-Rest-Device_(DynAReach).csv"), ...
    fullfile(data_dir, "Serie_3-Group_1-Task_24-Rest-Device_(DynAReach).csv"), ...
    fullfile(data_dir, "Serie_4-Group_1-Task_35-Rest-Device_(DynAReach).csv"), ...
    superimpose_dir ...
    );
superimpose_EMG( ...
    fullfile(data_dir, "Serie_1-Group_1-Task_4-Shoulder_Flexion-Baseline_(JAECO).csv"), ...
    fullfile(data_dir, "Serie_2-Group_1-Task_14-Shoulder_Flexion-Device_(DynAReach).csv"), ...
    fullfile(data_dir, "Serie_3-Group_1-Task_25-Shoulder_Flexion-Device_(DynAReach).csv"), ...
    fullfile(data_dir, "Serie_4-Group_1-Task_36-Shoulder_Flexion-Device_(DynAReach).csv"), ...
    superimpose_dir ...
    );
superimpose_EMG( ...
    fullfile(data_dir, "Serie_1-Group_1-Task_5-Elbow_Flexion-Baseline_(JAECO).csv"), ...
    fullfile(data_dir, "Serie_2-Group_1-Task_15-Elbow_Flexion-Device_(DynAReach).csv"), ...
    fullfile(data_dir, "Serie_3-Group_1-Task_26-Elbow_Flexion-Device_(DynAReach).csv"), ...
    fullfile(data_dir, "Serie_4-Group_1-Task_37-Elbow_Flexion-Device_(DynAReach).csv"), ...
    superimpose_dir ...
    );
% Group 2
superimpose_EMG( ...
    fullfile(data_dir, "Serie_1-Group_2-Task_6-Pointing_Task-Baseline_(JAECO).csv"), ...
    fullfile(data_dir, "Serie_2-Group_2-Task_17-Pointing_Task-Baseline_(JAECO).csv"), ...
    fullfile(data_dir, "Serie_3-Group_2-Task_27-Pointing_Task-Device_(DynAReach).csv"), ...
    fullfile(data_dir, "Serie_4-Group_2-Task_38-Pointing_Task-Device_(DynAReach).csv"), ...
    superimpose_dir ...
    );
superimpose_EMG( ...
    fullfile(data_dir, "Serie_1-Group_2-Task_7-HFT_Large_Light_Objects-Baseline_(JAECO).csv"), ...
    fullfile(data_dir, "Serie_2-Group_2-Task_18-HFT_Large_Light_Objects-Baseline_(JAECO).csv"), ...
    fullfile(data_dir, "Serie_3-Group_2-Task_28-HFT_Large_Light_Objects-Device_(DynAReach).csv"), ...
    fullfile(data_dir, "Serie_4-Group_2-Task_39-HFT_Large_Light_Objects-Device_(DynAReach).csv"), ...
    superimpose_dir ...
    );
superimpose_EMG( ...
    fullfile(data_dir, "Serie_1-Group_2-Task_8-Switch_Joystick_and_Grid_Game-Baseline_(JAECO).csv"), ...
    fullfile(data_dir, "Serie_2-Group_2-Task_19-Switch_Joystick_and_Grid_Game-Baseline_(JAECO).csv"), ...
    fullfile(data_dir, "Serie_3-Group_2-Task_29-Switch_Joystick_and_Grid_Game-Device_(DynAReach).csv"), ...
    fullfile(data_dir, "Serie_4-Group_2-Task_40-Switch_Joystick_and_Grid_Game-Device_(DynAReach).csv"), ...
    superimpose_dir ...
    );
% Group 3
superimpose_EMG( ...
    fullfile(data_dir, "Serie_1-Group_3-Task_9-JAMAR_Palmar_Grip-Baseline_(JAECO).csv"), ...
    fullfile(data_dir, "Serie_2-Group_3-Task_20-JAMAR_Palmar_Grip-Baseline_(JAECO).csv"), ...
    fullfile(data_dir, "Serie_3-Group_3-Task_31-JAMAR_Palmar_Grip-Baseline_(JAECO).csv"), ...
    fullfile(data_dir, "Serie_4-Group_3-Task_41-JAMAR_Palmar_Grip-Device_(DynAReach).csv"), ...
    superimpose_dir ...
    );
superimpose_EMG( ...
    fullfile(data_dir, "Serie_1-Group_3-Task_10-HFT_Feeding_task-Baseline_(JAECO).csv"), ...
    fullfile(data_dir, "Serie_2-Group_3-Task_21-HFT_Feeding_task-Baseline_(JAECO).csv"), ...
    fullfile(data_dir, "Serie_3-Group_3-Task_32-HFT_Feeding_task-Baseline_(JAECO).csv"), ...
    fullfile(data_dir, "Serie_4-Group_3-Task_42-HFT_Feeding_task-Device_(DynAReach).csv"), ...
    superimpose_dir ...
    );
superimpose_EMG( ...
    fullfile(data_dir, "Serie_1-Group_3-Task_11-Box_and_Blocs_Test-Baseline_(JAECO).csv"), ...
    fullfile(data_dir, "Serie_2-Group_3-Task_22-Box_and_Blocs_Test-Baseline_(JAECO).csv"), ...
    fullfile(data_dir, "Serie_3-Group_3-Task_33-Box_and_Blocs_Test-Baseline_(JAECO).csv"), ...
    fullfile(data_dir, "Serie_4-Group_3-Task_43-Box_and_Blocs_Test-Device_(DynAReach).csv"), ...
    superimpose_dir ...
    );
fprintf("All superimpose plots successfully created\n")

% -- Build CAI plots --
fprintf("\nComputing CAI for GUEA_ses1...\n")

% Store last Rest file per group
last_rest_file = "";

for k = 1:numel(files)

    file_name = string(files(k).name);
    file_path = fullfile(data_dir, file_name);

    % Parse filename
    info = parse_filename(file_path);

    % Skip invalid files
    if isnan(info.group) || info.task_name == ""
        continue;
    end

    % Identify Rest file (per group!)
    if contains(info.task_name, "Rest")
        last_rest_file = file_path;
        fprintf("Rest file detected: %s\n", file_name);
        continue;
    end

    % Find matching movement key
    keys_list = movements.keys();
    matchedKey = "";

    for i = 1:length(keys_list)
        if startsWith(info.task_name, keys_list(i))
            matchedKey = keys_list(i);
            break;
        end
    end

    % If match found → compute CAI
    if matchedKey ~= ""

        % Check if Rest exists
        if last_rest_file == ""
            warning("No Rest file available yet. Skipping %s", file_name);
            continue;
        end

        file_path_rest = last_rest_file;

        Ag = movements(matchedKey).agoniste;
        Antag = movements(matchedKey).antagoniste;

        for j = 1:length(Ag)
            find_CAI( ...
                last_rest_file, ...
                file_path, ...
                subjects(1).bmi, ...
                "Ag", Ag(j), ...
                "Antag", Antag(j), ...
                "title", info.task_name, ...
                "task", string(info.task), ...
                "save_folder", CAI_dir ...
            );
        end

    else
        warning("Task '%s' not recognized in dictionary.", info.task_name);
    end

end
fprintf("CAI computation completed for GUEA_ses1\n")


% ------- SUBJECT 2 / SESSION 1 --------

data_dir = "../data/RABA_ses1";
files = dir(fullfile(data_dir, '*.csv'));
all_tracks_dir = "../figs/RABA_ses1/all_tracks";
superimpose_dir = "../figs/RABA_ses1/superimpose";
CAI_dir = "../figs/RABA_ses1/CAI";

% -- Build all tracks plot --
fprintf("\nCreating all tracks plots for RABA_ses1...\n")
for k = 1:numel(files)

    % Construct full input path
    emg_Path = fullfile(files(k).folder, files(k).name);

    % Get file name
    file_name = string(files(k).name);
    
    % Get title
    title = strrep(file_name, '.csv', '');
    save_path = fullfile(all_tracks_dir, title);
    title = strrep(title, '_', ' ');
    title = strrep(title, '-', ' - ');
     
    % Show all tracks
    plot_tracks(emg_Path, save_path, title, subjects(1).bmi)

end
fprintf("All tracks plots successfully created\n")

% -- Build superimpose plots --
fprintf("\nCreating superimpose plots for RABA_ses1...\n")
% Group 1
superimpose_EMG( ...
    fullfile(data_dir, "Serie_1-Group_1-Task_3-Rest-Baseline_(JAECO).csv"), ...
    fullfile(data_dir, "Serie_2-Group_1-Task_13-Rest-Device_(DynAReach).csv"), ...
    fullfile(data_dir, "Serie_3-Group_1-Task_24-Rest-Device_(DynAReach).csv"), ...
    fullfile(data_dir, "Serie_4-Group_1-Task_35-Rest-Device_(DynAReach).csv"), ...
    superimpose_dir ...
    );
superimpose_EMG( ...
    fullfile(data_dir, "Serie_1-Group_1-Task_4-Shoulder_Flexion-Baseline_(JAECO).csv"), ...
    fullfile(data_dir, "Serie_2-Group_1-Task_14-Shoulder_Flexion-Device_(DynAReach).csv"), ...
    fullfile(data_dir, "Serie_3-Group_1-Task_25-Shoulder_Flexion-Device_(DynAReach).csv"), ...
    fullfile(data_dir, "Serie_4-Group_1-Task_36-Shoulder_Flexion-Device_(DynAReach).csv"), ...
    superimpose_dir ...
    );
superimpose_EMG( ...
    fullfile(data_dir, "Serie_1-Group_1-Task_5-Elbow_Flexion-Baseline_(JAECO).csv"), ...
    fullfile(data_dir, "Serie_2-Group_1-Task_15-Elbow_Flexion-Device_(DynAReach).csv"), ...
    fullfile(data_dir, "Serie_3-Group_1-Task_26-Elbow_Flexion-Device_(DynAReach).csv"), ...
    fullfile(data_dir, "Serie_4-Group_1-Task_37-Elbow_Flexion-Device_(DynAReach).csv"), ...
    superimpose_dir ...
    );
% Group 2
superimpose_EMG( ...
    fullfile(data_dir, "Serie_1-Group_2-Task_6-Pointing_Task-Baseline_(JAECO).csv"), ...
    fullfile(data_dir, "Serie_2-Group_2-Task_17-Pointing_Task-Baseline_(JAECO).csv"), ...
    fullfile(data_dir, "Serie_3-Group_2-Task_27-Pointing_Task-Device_(DynAReach).csv"), ...
    fullfile(data_dir, "Serie_4-Group_2-Task_38-Pointing_Task-Device_(DynAReach).csv"), ...
    superimpose_dir ...
    );
superimpose_EMG( ...
    fullfile(data_dir, "Serie_1-Group_2-Task_7-HFT_Large_Light_Objects-Baseline_(JAECO).csv"), ...
    fullfile(data_dir, "Serie_2-Group_2-Task_18-HFT_Large_Light_Objects-Baseline_(JAECO).csv"), ...
    fullfile(data_dir, "Serie_3-Group_2-Task_28-HFT_Large_Light_Objects-Device_(DynAReach).csv"), ...
    fullfile(data_dir, "Serie_4-Group_2-Task_39-HFT_Large_Light_Objects-Device_(DynAReach).csv"), ...
    superimpose_dir ...
    );
superimpose_EMG( ...
    fullfile(data_dir, "Serie_1-Group_2-Task_8-Switch_Joystick_and_Grid_Game-Baseline_(JAECO).csv"), ...
    fullfile(data_dir, "Serie_2-Group_2-Task_19-Switch_Joystick_and_Grid_Game-Baseline_(JAECO).csv"), ...
    fullfile(data_dir, "Serie_3-Group_2-Task_29-Switch_Joystick_and_Grid_Game-Device_(DynAReach).csv"), ...
    fullfile(data_dir, "Serie_4-Group_2-Task_40-Switch_Joystick_and_Grid_Game-Device_(DynAReach).csv"), ...
    superimpose_dir ...
    );
% Group 3
superimpose_EMG( ...
    fullfile(data_dir, "Serie_1-Group_3-Task_9-JAMAR_Palmar_Grip-Baseline_(JAECO).csv"), ...
    fullfile(data_dir, "Serie_2-Group_3-Task_20-JAMAR_Palmar_Grip-Baseline_(JAECO).csv"), ...
    fullfile(data_dir, "Serie_3-Group_3-Task_31-JAMAR_Palmar_Grip-Baseline_(JAECO).csv"), ...
    fullfile(data_dir, "Serie_4-Group_3-Task_41-JAMAR_Palmar_Grip-Device_(DynAReach).csv"), ...
    superimpose_dir ...
    );
superimpose_EMG( ...
    fullfile(data_dir, "Serie_1-Group_3-Task_10-HFT_Feeding_task-Baseline_(JAECO).csv"), ...
    fullfile(data_dir, "Serie_2-Group_3-Task_21-HFT_Feeding_task-Baseline_(JAECO).csv"), ...
    fullfile(data_dir, "Serie_3-Group_3-Task_32-HFT_Feeding_task-Baseline_(JAECO).csv"), ...
    fullfile(data_dir, "Serie_4-Group_3-Task_42-HFT_Feeding_task-Device_(DynAReach).csv"), ...
    superimpose_dir ...
    );
superimpose_EMG( ...
    fullfile(data_dir, "Serie_1-Group_3-Task_11-Box_and_Blocs_Test-Baseline_(JAECO).csv"), ...
    fullfile(data_dir, "Serie_2-Group_3-Task_22-Box_and_Blocs_Test-Baseline_(JAECO).csv"), ...
    fullfile(data_dir, "Serie_3-Group_3-Task_33-Box_and_Blocs_Test-Baseline_(JAECO).csv"), ...
    fullfile(data_dir, "Serie_4-Group_3-Task_43-Box_and_Blocs_Test-Device_(DynAReach).csv"), ...
    superimpose_dir ...
    );
fprintf("All superimpose plots successfully created\n")

% -- Build CAI plots --
fprintf("\nComputing CAI for RABA_ses1...\n")

% Store last Rest file per group
last_rest_file = "";

for k = 1:numel(files)

    file_name = string(files(k).name);
    file_path = fullfile(data_dir, file_name);

    % Parse filename
    info = parse_filename(file_path);

    % Skip invalid files
    if isnan(info.group) || info.task_name == ""
        continue;
    end

    % Identify Rest file (per group!)
    if contains(info.task_name, "Rest")
        last_rest_file = file_path;
        fprintf("Rest file detected: %s\n", file_name);
        continue;
    end

    % Find matching movement key
    keys_list = movements.keys();
    matchedKey = "";

    for i = 1:length(keys_list)
        if startsWith(info.task_name, keys_list(i))
            matchedKey = keys_list(i);
            break;
        end
    end

    % If match found → compute CAI
    if matchedKey ~= ""

        % Check if Rest exists
        if last_rest_file == ""
            warning("No Rest file available yet. Skipping %s", file_name);
            continue;
        end

        file_path_rest = last_rest_file;

        Ag = movements(matchedKey).agoniste;
        Antag = movements(matchedKey).antagoniste;

        for j = 1:length(Ag)
            find_CAI( ...
                last_rest_file, ...
                file_path, ...
                subjects(1).bmi, ...
                "Ag", Ag(j), ...
                "Antag", Antag(j), ...
                "title", info.task_name, ...
                "task", string(info.task), ...
                "save_folder", CAI_dir ...
            );
        end

    else
        warning("Task '%s' not recognized in dictionary.", info.task_name);
    end

end
fprintf("CAI computation completed for RABA_ses1\n")
